### ISSUE TITLE
Issue with installing Django.

### ISSUE THREAD

**Issue by omps** [avocado-framework/avocado-server#57]
Downloading Django-2.0.tar.gz (8.0MB)
    100% |████████████████████████████████| 8.0MB 103kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qItdzL/django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'

**Comment by omps** [comment]
https://stackoverflow.com/questions/42196124/there-are-errors-when-i-install-django-by-git


 The last Django version does not support python 2.7.If you really want to use python 2.7 and also use Django you should install a previous Django version.The latest supported is: 1.11Therefore, just run:
    
    pip install django==1.11

@ldoktor Version no. need to be updated in the avocado-server documentation.

**Comment by omps** [comment]
submitter PR #58
